// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class LinksNavBarTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void linksNavBar() {
    driver.Navigate().GoToUrl("https://phptravels.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) .icon")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/flight-booking-engine/\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) .icon")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/flight-booking-system/\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) .icon")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/flight-booking-software/\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) .icon")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/flight-ticket-booking-software/\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) .icon")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/flight-ticket-reservation-system/\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) .icon")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/car-rental-software/\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) .icon")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/best-bus-booking-software/\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) .icon")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/best-booking-agency-software/\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) > .reset")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/best-online-booking-software/\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) > .reset")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/arabic-travel-system\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) .icon")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/destination-management-system\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) .icon")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/b2b-booking-engine\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) .icon")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/b2c-booking-system\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) .icon")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/travel-management-system\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) > .reset")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/travel-agents-system\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) > .reset")).Click();
    js.ExecuteScript("window.scrollTo(0,0)");
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/online-travel-agencies-system\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) > .reset")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/travel-wholesalers-system\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) .icon")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/tour-operators-solution\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) > .reset")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/channel-managers-integration\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) > .reset")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/travel-cms-integration\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) > .reset")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/travel-branches-set-up\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) > .reset")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/travel-accounting-systems-integration\')]")).Click();
    driver.FindElement(By.CssSelector(".btn-success")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) > .reset")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/travel-payment-gateways-integration\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) > .reset")).Click();
    js.ExecuteScript("window.scrollTo(0,0)");
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/custom-travel-solutions\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) .icon")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/hotelbeds-api-xml-integration\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) > .reset")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/cartrawler-api-integration\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) > .reset")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/pkfare-api-integration\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) > .reset")).Click();
    js.ExecuteScript("window.scrollTo(0,0)");
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/travelport-api-integration\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) > .reset")).Click();
    js.ExecuteScript("window.scrollTo(0,0)");
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/travelport-gds-integration\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) > .reset")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/sabre-gds-api-integration\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) > .reset")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/sabre-api-integration\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) > .reset")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/travel-api-integration\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) > .reset")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/what-is-api-integration\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) > .reset")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/api-integration\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) > .reset")).Click();
    js.ExecuteScript("window.scrollTo(0,0)");
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/flight-api\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) > .reset")).Click();
    driver.FindElement(By.XPath("//a[contains(@href, \'https://phptravels.com/b2b-hotel-booking\')]")).Click();
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) > .reset")).Click();
    js.ExecuteScript("window.scrollTo(0,0)");
    driver.FindElement(By.CssSelector(".yx-njw:nth-child(38) > .yx-njx")).Click();
    driver.FindElement(By.XPath("(//a[contains(@href, \'https://phptravels.com/\')])[111]")).Click();
  }
}
