// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class NavBarTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  public string waitForWindow(int timeout) {
    try {
      Thread.Sleep(timeout);
    } catch(Exception e) {
      Console.WriteLine("{0} Exception caught.", e);
    }
    var whNow = ((IReadOnlyCollection<object>)driver.WindowHandles).ToList();
    var whThen = ((IReadOnlyCollection<object>)vars["WindowHandles"]).ToList();
    if (whNow.Count > whThen.Count) {
      return whNow.Except(whThen).First().ToString();
    } else {
      return whNow.First().ToString();
    }
  }
  [Test]
  public void navBar() {
    driver.Navigate().GoToUrl("https://phptravels.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
    {
      var element = driver.FindElement(By.LinkText("Docs"));
      //Actions builder = new Actions(driver);
      //builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.XPath("//div[@id=\'mega-nav-navigation\']/div/ul/li[4]/button"));
      //Actions builder = new Actions(driver);
      //builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.TagName("body"));
      //Actions builder = new Actions(driver);
      //builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.LinkText("Demo")).Click();
    {
      var element = driver.FindElement(By.XPath("//div[@id=\'mega-nav-navigation\']/div/ul/li[4]/button"));
      //Actions builder = new Actions(driver);
      //builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.TagName("body"));
      //Actions builder = new Actions(driver);
      //builder.MoveToElement(element, 0, 0).Perform();
    }
    Assert.That(driver.FindElement(By.XPath("//strong")).Text, Is.EqualTo("Demo Credentials for Frontend and Backend"));
    {
      var element = driver.FindElement(By.LinkText("Pricing"));
      //Actions builder = new Actions(driver);
      //builder.MoveToElement(element).Perform();
    }
    driver.FindElement(By.LinkText("Pricing")).Click();
    js.ExecuteScript("window.scrollTo(0,243.1999969482422)");
    Assert.That(driver.FindElement(By.XPath("//main[@id=\'Main\']/div/div[3]/table/thead/tr/th[2]/div/h3/strong")).Text, Is.EqualTo("Basic"));
    Assert.That(driver.FindElement(By.XPath("//main[@id=\'Main\']/div/div[3]/table/tbody/tr/td/span[2]")).Text, Is.EqualTo("$499"));
    Assert.That(driver.FindElement(By.XPath("//main[@id=\'Main\']/div/div[3]/table/thead/tr/th[3]/div/h3/strong")).Text, Is.EqualTo("Pro"));
    Assert.That(driver.FindElement(By.XPath("//main[@id=\'Main\']/div/div[3]/table/tbody/tr/td[2]/span[2]")).Text, Is.EqualTo("$999"));
    Assert.That(driver.FindElement(By.XPath("//main[@id=\'Main\']/div/div[3]/table/thead/tr/th[4]/div/h3/strong")).Text, Is.EqualTo("Enterprise"));
    Assert.That(driver.FindElement(By.XPath("//main[@id=\'Main\']/div/div[3]/table/tbody/tr/td[3]/span[2]")).Text, Is.EqualTo("$1499"));
    //driver.FindElement(By.CssSelector(".yx-njv:nth-child(4) .icon")).Click();
    //driver.FindElement(By.CssSelector(".yx-njz path:nth-child(2)")).Click();
    //driver.FindElement(By.CssSelector(".yx-njv:nth-child(6) .icon")).Click();
    //driver.FindElement(By.CssSelector(".yx-njz path:nth-child(1)")).Click();
    //driver.FindElement(By.CssSelector(".yx-njv:nth-child(7) path:nth-child(1)")).Click();
    //driver.FindElement(By.CssSelector(".yx-njz .icon")).Click();
    //driver.FindElement(By.CssSelector(".yx-njv:nth-child(8) .icon")).Click();
    //driver.FindElement(By.CssSelector(".yx-njz path:nth-child(1)")).Click();
    vars["WindowHandles"] = driver.WindowHandles;
    driver.FindElement(By.LinkText("Docs")).Click();
    vars["win8244"] = waitForWindow(2000);
    vars["root"] = driver.CurrentWindowHandle;
    driver.SwitchTo().Window(vars["win8244"].ToString());
    driver.Close();
    driver.SwitchTo().Window(vars["root"].ToString());
    vars["WindowHandles"] = driver.WindowHandles;
    driver.FindElement(By.LinkText("Blog")).Click();
    vars["win6405"] = waitForWindow(2000);
    driver.SwitchTo().Window(vars["win6405"].ToString());
    driver.Close();
    driver.SwitchTo().Window(vars["root"].ToString());
  }
}
