// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class ProductProductsNavBarTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void productProductsNavBar() {
    driver.Navigate().GoToUrl("https://phptravels.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
    Thread.Sleep(2000);
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(4) .icon")).Click();
    driver.FindElement(By.XPath("//div[@id=\'mega-nav-navigation\']/div/ul/li[4]/div/div/ul[2]/li[2]/a")).Click();
    Thread.Sleep(2000);
    Assert.That(driver.FindElement(By.CssSelector(".upper")).Text, Is.EqualTo("PRODUCT SERVICES"));
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(4) .icon")).Click();
    driver.FindElement(By.XPath("//div[@id=\'mega-nav-navigation\']/div/ul/li[4]/div/div/ul[2]/li[3]/a")).Click();
    Thread.Sleep(2000);
    Assert.That(driver.FindElement(By.CssSelector(".title")).Text, Is.EqualTo("INTEGRATIONS INFORMATION"));
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(4) .icon")).Click();
    driver.FindElement(By.XPath("//div[@id=\'mega-nav-navigation\']/div/ul/li[4]/div/div/ul[2]/li[4]/a")).Click();
    Thread.Sleep(2000);
    Assert.That(driver.FindElement(By.CssSelector(".text > .title")).Text, Is.EqualTo("WE LOVE CUSTOMIZATION'S"));
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(4) > .reset")).Click();
    driver.FindElement(By.XPath("//div[@id=\'mega-nav-navigation\']/div/ul/li[4]/div/div/ul[2]/li[5]/a")).Click();
    Thread.Sleep(2000);
    Assert.That(driver.FindElement(By.CssSelector(".upper")).Text, Is.EqualTo("EXPEDIA API INTEGRATION XML"));
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(4) > .reset")).Click();
    driver.FindElement(By.XPath("//div[@id=\'mega-nav-navigation\']/div/ul/li[4]/div/div/ul[2]/li[6]/a")).Click();
    Thread.Sleep(2000);
    Assert.That(driver.FindElement(By.CssSelector(".upper")).Text, Is.EqualTo("SUPPLIERS LIST"));
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(4) > .reset")).Click();
    driver.FindElement(By.XPath("//div[@id=\'mega-nav-navigation\']/div/ul/li[4]/div/div/ul[2]/li[7]/a")).Click();
    Thread.Sleep(2000);
    Assert.That(driver.FindElement(By.CssSelector(".upper")).Text, Is.EqualTo("TRAVEL XML API INTEGRATIONS PROVIDERS"));
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(4) > .reset")).Click();
    driver.FindElement(By.XPath("//div[@id=\'mega-nav-navigation\']/div/ul/li[4]/div/div/ul[2]/li[8]/a")).Click();
    Thread.Sleep(2000);
    Assert.That(driver.FindElement(By.CssSelector(".upper")).Text, Is.EqualTo("TECHNOLOGY"));
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(4) .icon")).Click();
    driver.FindElement(By.XPath("//div[@id=\'mega-nav-navigation\']/div/ul/li[4]/div/div/ul[2]/li[9]/a")).Click();
    Thread.Sleep(2000);
    Assert.That(driver.FindElement(By.CssSelector(".upper")).Text, Is.EqualTo("REQUIREMENTS"));
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(4) > .reset")).Click();
    driver.FindElement(By.XPath("//div[@id=\'mega-nav-navigation\']/div/ul/li[4]/div/div/ul[2]/li[10]/a")).Click();
    Thread.Sleep(2000);
    Assert.That(driver.FindElement(By.CssSelector(".upper")).Text, Is.EqualTo("CHANGELOG"));
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(4) > .reset")).Click();
    driver.FindElement(By.XPath("//div[@id=\'mega-nav-navigation\']/div/ul/li[4]/div/div/ul[2]/li[11]/a")).Click();
    Thread.Sleep(2000);
    Assert.That(driver.FindElement(By.CssSelector(".cw:nth-child(1)")).Text, Is.EqualTo("MOBILE APPLICATIONS"));
    driver.Navigate().Back();
    Thread.Sleep(1000);
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(4) > .reset")).Click();
    driver.FindElement(By.XPath("//div[@id=\'mega-nav-navigation\']/div/ul/li[4]/div/div/ul[2]/li[12]/a")).Click();
    Thread.Sleep(2000);
    Assert.That(driver.FindElement(By.CssSelector(".upper")).Text, Is.EqualTo("DESKTOP APPLICATIONS"));
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(4) .icon")).Click();
    driver.FindElement(By.XPath("//div[@id=\'mega-nav-navigation\']/div/ul/li[4]/div/div/ul[2]/li[13]/a")).Click();
    Thread.Sleep(2000);
    Assert.That(driver.FindElement(By.CssSelector(".upper")).Text, Is.EqualTo("ROAD MAP"));
    //Thread.Sleep(9000); Problem below this line
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(4) .icon")).Click();
    //Thread.Sleep(9000); Problem above this line
    //driver.FindElement(By.XPath("//div[@id=\'mega-nav-navigation\']/div/ul/li[4]/div/div/ul[2]/li[14]/a")).Click();
    //Thread.Sleep(9000);  //problem above this line
    ////Assert.That(driver.FindElement(By.CssSelector(".upper")).Text, Is.EqualTo("UPDATES"));
    //driver.FindElement(By.CssSelector(".yx-njv:nth-child(4) > .reset")).Click();
    //driver.FindElement(By.XPath("//div[@id=\'mega-nav-navigation\']/div/ul/li[4]/div/div/ul[2]/li[15]/a")).Click();
    //Thread.Sleep(2000);
    //Assert.That(driver.FindElement(By.CssSelector(".upper")).Text, Is.EqualTo("HOW TO GET STARTED!"));
  }
}
