// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class ProductNavBarTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void productNavBar() {
    driver.Navigate().GoToUrl("https://phptravels.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1552, 840);
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(4) .icon")).Click();
    driver.FindElement(By.XPath("//div[@id=\'mega-nav-navigation\']/div/ul/li[4]/div/div/ul/li[2]/a")).Click();
    Thread.Sleep(3000);
    Assert.That(driver.FindElement(By.CssSelector(".upper")).Text, Is.EqualTo("HOTELS MODULE FEATURES"));
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(4) > .reset")).Click();
    driver.FindElement(By.XPath("//div[@id=\'mega-nav-navigation\']/div/ul/li[4]/div/div/ul/li[3]/a")).Click();
    Thread.Sleep(3000);
    Assert.That(driver.FindElement(By.XPath("//main[@id=\'Main\']/section/div/div/div/div/h2")).Text, Is.EqualTo("FLIGHTS RESERVATION MODULE"));
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(4) > .reset")).Click();
    driver.FindElement(By.XPath("//div[@id=\'mega-nav-navigation\']/div/ul/li[4]/div/div/ul/li[4]/a")).Click();
    Thread.Sleep(3000);
    Assert.That(driver.FindElement(By.XPath("//main[@id=\'Main\']/section/div/div/div/div/h2")).Text, Is.EqualTo("TOURS MODULE FEATURES"));
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(4) > .reset")).Click();
    driver.FindElement(By.XPath("//div[@id=\'mega-nav-navigation\']/div/ul/li[4]/div/div/ul/li[5]/a")).Click();
    Thread.Sleep(3000);
    Assert.That(driver.FindElement(By.XPath("//main[@id=\'Main\']/section/div/div/div/div/h2")).Text, Is.EqualTo("CARS MODULE FEATURES"));
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(4) > .reset")).Click();
    driver.FindElement(By.XPath("//div[@id=\'mega-nav-navigation\']/div/ul/li[4]/div/div/ul/li[6]/a")).Click();
    Thread.Sleep(3000);
    Assert.That(driver.FindElement(By.XPath("//main[@id=\'Main\']/section/div/div/div/div/h2")).Text, Is.EqualTo("OFFERS MODULE FEATURES"));
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(4) > .reset")).Click();
    driver.FindElement(By.XPath("//div[@id=\'mega-nav-navigation\']/div/ul/li[4]/div/div/ul/li[7]/a")).Click();
    Thread.Sleep(3000);
    Assert.That(driver.FindElement(By.XPath("//main[@id=\'Main\']/section/div/div/div/div/h2")).Text, Is.EqualTo("BLOGS AND ARTICLES MODULE FEATURES"));
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(4) > .reset")).Click();
    driver.FindElement(By.XPath("//div[@id=\'mega-nav-navigation\']/div/ul/li[4]/div/div/ul/li[8]/a")).Click();
    Thread.Sleep(3000);
    Assert.That(driver.FindElement(By.XPath("//main[@id=\'Main\']/section/div/div/div/div/h2")).Text, Is.EqualTo("NEWSLETTER MODULE FEATURES"));
    driver.FindElement(By.CssSelector(".yx-njv:nth-child(4) > .reset")).Click();
    driver.FindElement(By.XPath("//div[@id=\'mega-nav-navigation\']/div/ul/li[4]/div/div/ul/li[9]/a")).Click();
    Thread.Sleep(3000);
    Assert.That(driver.FindElement(By.XPath("//main[@id=\'Main\']/section/div/div/div/div/h2")).Text, Is.EqualTo("CMS MODULE FEATURES"));
  }
}
